### ISSUE TITLE
Client search correct type

### ISSUE THREAD

**Issue by Seymur** [ElmanAASTANOV/frontend-coding-assignment#2]
https://github.com/ElmanAASTANOV/frontend-coding-assignment/blob/2fe97b824360c042bf6e9427c034de7785d9dd05/pages/search-client.tsx#L15
Here you should not cast type to `string`, as searchQuery can also be `string[]`, so you should handle the case where searchQuery will be `string[]` as well

**Comment by ElmanAASTANOV** [comment]
I solved it but fetching data api just only accept string param. Therefore I type casted to string. I changed to api parametr type
